### PR TITLE
SUSE Manager 4.2.0

### PR DESCRIPTION
**Pull request by juliogonzalez**

### CODE REVIEW

**Comment by lslezak** [comment]
I guess we need also to update https://github.com/yast/skelcd-control-leanos/blob/master/control/control.leanos.xml#L181-L201 (that list is used for registering the products on the Online medium via SCC).

**Comment by juliogonzalez** [comment]
@lslezak I guess so... but I am not sure I am understanding what you mean "registering the products on the Online medium via SCC". Do you mean registering the products during the setup via the Unified Installer or what exactly?

I was not aware of that `skelcd-control-leanos`. Who is responsible of keeping this package updated? We (SUSE Manager as well? If so: is there any other `skelcd-control-*` packages that we should consider as well?

**Comment by lslezak** [comment]
> Do you mean registering the products during the setup via the Unified Installer or what exactly?

Yes, that's it. But we ship two media sets - the Online and Full ISOs, both can be registered against SCC.

The Full medium contains RPMs so YaST can find the products (and their versions) by querying the available RPMs. But the Online medium does not contain any RPM package, it's just a bootable medium containing the installer. And in that case YaST does not know which products can be registered via SCC, there are no RPMs to check.

Unfortunately SCC does not provide any API to read the products which can be registered. For that case we have hardcoded the product list into the `skelcd-control-leanos` package which is included in the installer.

So ideally the `skelcd-control-leanos` content should be synchronized with the Full medium content so both media allow registering the same products.

> Who is responsible of keeping this package updated? We (SUSE Manager as well?

Ideally the product managers, but in reality we (the YaST team) keep it updated, we just need to know when/what. Somebody has to tell us what is going on...

> If so: is there any other `skelcd-control-*` packages that we should consider as well?

No, only the `skelcd-control-leanos` is a special package for the unified installer, then there are per product control files (like this 
`skelcd-control-suse-manager-proxy`).

**Comment by juliogonzalez** [comment]
> Ideally the product managers, but in reality we (the YaST team) keep it updated, we just need to know when/what. Somebody has to tell us what is going on...

I can take care of that as Release Engineer for SUSE Manager if you want, as in the end I and modifying the the other skelcd-control packages with the PRs, the skelcd packages at the SLE codestreams, etc :-)

I will add this to my doc and will create a PR for https://github.com/yast/skelcd-control-leanos/blob/master/control/control.leanos.xml in a few minutes.

**Review by lslezak — APPROVED** [review]

**Pull request merged**
